services:

  filebrowser:
    image: ghcr.io/gtsteffaniak/filebrowser:beta
    container_name: filebrowser
    ports:
      - "8900:80"
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./data:/home/filebrowser/data
      - ./files:/files
#      - ./images:/images
    environment:
      - FILEBROWSER_CONFIG=data/config.yaml
